#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "conc_of_meas_anal_1.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:2]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

set label '{/Symbol p}(q)' at 0.05, 1.5 tc rgb "$light"

N = 10.0
sigma2 = 1 / N

plot \
exp(- 0.5 * x * x / sigma2) / sqrt(2 * pi * sigma2) with lines lt 1 lw 4 lc rgb '$light' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "conc_of_meas_anal_2.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:2]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

set label '{/Symbol p}(q)' at 0.05, 1.5 tc rgb "$light"
set label "dq" at 1.2, 2.55 tc rgb "$mid"

N = 10.0
sigma2 = 1 / N

plot \
exp(- 0.5 * x * x / sigma2) / sqrt(2 * pi * sigma2) \
with lines lt 1 lw 4 lc rgb '$light' notitle, \
x**(N - 1) with lines lt 1 lw 4 lc rgb '$mid' notitle


END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "conc_of_meas_anal_3.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:2]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

set label '{/Symbol p}(q)' at 0.05, 1.5 tc rgb "$light"
set label "dq" at 1.2, 2.55 tc rgb "$mid"
set label 'dq {/Symbol p}(q)' at 1.3, 1.0 tc rgb "$dark"

N = 10.0
sigma2 = 1 / N

plot \
exp(- 0.5 * x * x / sigma2) / sqrt(2 * pi * sigma2) \
with lines lt 1 lw 4 lc rgb '$light' notitle, \
x**(N - 1) with lines lt 1 lw 4 lc rgb '$mid' notitle, \
exp(  log(2.0) - lgamma(0.5 * N) \
- 0.5 * N * log(2.0 * sigma2) \
+ (N - 1) * log(x) - 0.5 * x * x / sigma2 ) \
with lines lt 1 lw 4 lc rgb '$dark' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "conc_of_meas_anal_4.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:2]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

deltaX=0.006
deltaY=deltaX * 1.5

set obj rect from 0.95 - 0.4, 0 to 0.95 + 0.4, 3 fs noborder solid 1.0 fc rgb '#EEEEEE'

set label 'dq {/Symbol p}(q)' at 1.3, 1.0 tc rgb "$dark"

N = 10.0
sigma2 = 1 / N

plot \
exp(  log(2.0) - lgamma(0.5 * N) \
- 0.5 * N * log(2.0 * sigma2) \
+ (N - 1) * log(x) - 0.5 * x * x / sigma2 ) \
with lines lt 1 lw 4 lc rgb '$dark' notitle

END

