#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "prior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + log(0.0752) + log(0.02005) + 8.73885035992 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "indiv_likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

splot  0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + 6.09159495082 - 8.73885035992 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "weak_marginal_likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

sigma_margin = 5
N_margin = 9.0
y_ave = -1.677848
y2_ave = 19.78904

splot  0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + 0.5 * N_margin * log(sigma_margin**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma_margin**2 + exp(2 * y)) \
     - 12.2303489259 - 8.73885035992 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "strong_marginal_likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

sigma_margin = 0.25
N_margin = 9
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + 0.5 * N_margin * log(sigma_margin**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma_margin**2 + exp(2 * y)) \
     - 5.68491118869 - 8.73885035992 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "indiv_posterior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + 0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + log(0.075) + log(0.02) + 6.09159495082 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "weak_marginal_posterior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

sigma_margin = 5
N_margin = 9.0
y_ave = -1.677848
y2_ave = 19.78904

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + 0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + 0.5 * N_margin * log(sigma_margin**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma_margin**2 + exp(2 * y)) \
     + log(0.075) + log(0.02) - 12.2303489259 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "strong_marginal_posterior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma_indiv = 0.25
y_indiv = 1.30321992

sigma_margin = 0.25
N_margin = 9
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + 0.5 * ( (x * exp(y) - y_indiv) / sigma_indiv )**2 \
     + 0.5 * N_margin * log(sigma_margin**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma_margin**2 + exp(2 * y)) \
     + log(0.075) + log(0.02) - 5.68491118869 notitle

END
