#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

simu_names=(matern_12 matern_52 exp_quad)

for simu in ${simu_names[@]}; do

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output "prior_${simu}.eps"

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-10:10]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".i."p prior_${simu}.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 500 - 11):1:(i) w l lt 1 lw 3 lc palette notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output "post_${simu}.eps"

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-10:10]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".i."p post_${simu}.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 500 - 11):1:(i) w l lt 1 lw 3 lc palette notitle, \
'data.csv' u 1:2 w p pt 7 ps 4 lc rgb "white" notitle, \
'data.csv' u 1:2 w p pt 7 ps 3 lc rgb "black" notitle

END

done

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output "post_exp_quad_no_data.eps"

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-10:10]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".i."p post_exp_quad.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 500 - 11):1:(i) w l lt 1 lw 3 lc palette notitle, \

END
