#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "banana_density.eps"

set border 0 lw 2

set lmargin screen 0
set rmargin screen 1
set bmargin screen 0
set tmargin screen 1

set pm3d map implicit at s

set title ""

set xtics scale 0
set xlabel ''
set xrange[-30:30]
set format x ''

set ytics nomirror scale 0
set ylabel ''
set yrange[-25:5]
set format y ''

set zlabel ''
set zrange[0:75]
unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 400
set isosamples 400

splot exp(-0.5 * (0.01 * x * x + (y + 0.03 * x * x - 3) * (y + 0.03 * x * x - 3) ) ) \
 notitle
END


gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "banana_integrand.eps"

set border 0 lw 2

set lmargin screen 0
set rmargin screen 1
set bmargin screen 0
set tmargin screen 1

set pm3d map implicit at s

set title ""

set xtics scale 0
set xlabel ''
set xrange[-30:30]
set format x ''

set ytics nomirror scale 0
set ylabel ''
set yrange[-25:5]
set format y ''

set zlabel ''
set zrange[0:75]
unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 400
set isosamples 400

splot exp(-0.5 * (0.01 * x * x + (y + 0.03 * x * x - 3) * (y + 0.03 * x * x - 3) ) ) * x * x \
 notitle
END
