#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 6, 4
set output "funnel.eps"

set pm3d map implicit at s

set title ""

set border 0 lw 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirro scale 0
set xlabel ''
set xrange[-10:10]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[-6:4]

set zlabel ''
set zrange[-10:10]
unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 300
set isosamples 300

splot (y + 0.5 * (x**2 * exp(-y) + y**2 / 1.0 )) notitle

END
