#!/bin/bash

hyperlight="#F5ECEC"
sublight="#EBDADA"
light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 55' size 5, 4
set output "funnel_trace0.eps"

set datafile separator ','

set border 3 lw 2

set lmargin screen 0.005
set rmargin screen 0.995
set bmargin screen 0.2
set tmargin screen 1

set title ""

set xtics scale 0
set format x ''
set xlabel 'Iteration' offset 0, 0.25
set xrange[0:700]

set ytics scale 0
set ylabel ''
set format y ''
set yrange[-5:5]

plot 1 / 0 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 55' size 5, 4
set output "funnel_trace1.eps"

set datafile separator ','

set border 3 lw 2

set lmargin screen 0.005
set rmargin screen 0.995
set bmargin screen 0.2
set tmargin screen 1

set title ""

set xtics scale 0
set format x ''
set xlabel 'Iteration' offset 0, 0.25
set xrange[0:700]

set ytics scale 0
set ylabel ''
set format y ''
set yrange[-5:5]

plot \
"funnel_trace.csv" using (3*\$0):5 every 3::0::400 with points pt 7 ps 2 lc rgb '$dark' notitle, \
"funnel_trace.csv" using (3*\$0):5 every 3::0::400 with points pt 7 ps 1 lc rgb '$light' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 55' size 5, 4
set output "funnel_trace2.eps"

set datafile separator ','
 
set border 3 lw 2

set lmargin screen 0.005
set rmargin screen 0.995
set bmargin screen 0.2
set tmargin screen 1

set title ""

set xtics scale 0
set format x ''
set xlabel 'Iteration' offset 0, 0.25
set xrange[0:700]

set ytics scale 0
set ylabel ''
set format y ''
set yrange[-5:5]

plot \
"funnel_trace.csv" using (3*\$0):5 every 3::0::400 \
with points pt 7 ps 2 lc rgb '$light' notitle, \
"funnel_trace.csv" using (3*\$0):5 every 3::0::400 \
with points pt 7 ps 1 lc rgb '$hyperlight' notitle, \
"funnel_trace.csv" using (3*\$0+400):5 every 3::400::600 \
with points pt 7 ps 2 lc rgb '$dark' notitle, \
"funnel_trace.csv" using (3*\$0+400):5 every 3::400::600 \
with points pt 7 ps 1 lc rgb '$light' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 55' size 5, 4
set output "funnel_trace3.eps"

set datafile separator ','

set border 3 lw 2

set lmargin screen 0.005
set rmargin screen 0.995
set bmargin screen 0.2
set tmargin screen 1

set title ""

set xtics scale 0
set format x ''
set xlabel 'Iteration' offset 0, 0.25
set xrange[0:700]

set ytics scale 0
set ylabel ''
set format y ''
set yrange[-5:5]

plot \
"funnel_trace.csv" using (3*\$0):5 every 3::0::600 \
with points pt 7 ps 2 lc rgb '$light' notitle, \
"funnel_trace.csv" using (3*\$0):5 every 3::0::600 \
with points pt 7 ps 1 lc rgb '$hyperlight' notitle, \
"funnel_trace.csv" using (3*\$0+600):5 every 3::600::700 \
with points pt 7 ps 2 lc rgb '$dark' notitle, \
"funnel_trace.csv" using (3*\$0+600):5 every 3::600::700 \
with points pt 7 ps 1 lc rgb '$light' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 55' size 5.5, 4
set output "funnel_bias_axes.eps"

set datafile separator ','

set border 3 lw 2

set lmargin screen 0.075
set rmargin screen 1
set bmargin screen 0.2
set tmargin screen 1

set title ""

set xtics scale 0
set format x ''
set xlabel 'Iteration' offset 0, 0.25
set xrange[0:700]

set ytics scale 0 (0) offset 0.25, 0
set ylabel ''
set yrange[-5:5]

plot 0 w l lw 4 lc "#777777" dt "-" notitle

END
