#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-75:75]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

set datafile separator ','

# 0.5 * (x * exp(-y) )**2 + y

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + log(0.0752) + log(0.02005) + 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "inverted_funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-75:75]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

set datafile separator ','

splot  0.5 * (x * exp(y) / 100 )**2 - y + log(100) \
     + 0.5 * (exp(y) / 3)**2 - y \
     + log(0.0752) + log(0.02005) + 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "sum_funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-75:75]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

set datafile separator ','

log_pi1(x, y) = - (  0.5 * x**2  \
                   + 0.5 * (exp(y) / 3)**2 - y \
                   + log(0.0752) + log(0.02005) + 8.732925977)
                   
log_pi2(x, y) = - (  0.5 * (x * exp(y) / 100 )**2 - y + log(100) \
                   + 0.5 * (exp(y) / 3)**2 - y \
                   + log(0.0752) + log(0.02005) + 8.732925977)

log_sum_exp(x, y) = x > y ? x + log(1 + exp(y - x)) : y + log(1 + exp(x - y))

splot -log_sum_exp(log(0.1) + log_pi1(x, y), log(0.9) + log_pi2(x, y)) notitle

END

