#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

priors=("normal" "normal_mixture" "laplace" "cauchy")
prior_idxs=(5 9 13 17)
likelihoods=("wide" "narrow_small" "narrow_large")

i=0
while [ $i -lt 4 ]; do
  j=0
  while [ $j -lt 3 ]; do
    
    let like_idx=$j+2
    let post_idx=prior_idxs[$i]+$j+1

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "${priors[$i]}_${likelihoods[$j]}.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange [0:0.6]

plot  \
"../density_comps.csv" u 1:${prior_idxs[$i]} w l lt 1 lw 2 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:$like_idx w l lt 1 lw 2 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:$post_idx w l lt 1 lw 2 lc rgb "$light" notitle

END

    let ++j
  done 
  let ++i
done
