#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "gamma_pdf.eps"

set border 3 lw 2

set title ""

set lmargin screen 0.125
set rmargin screen 0.875

set xtics out nomirror
set xlabel 'x'
set xrange[0:20]

set ytics scale 0
set ylabel "Probability Density Function"
set format y ''

alpha = 20
beta = 2

gamma_pdf(x, alpha, beta) = exp(alpha * log(beta) - lgamma(alpha) + (alpha - 1) * log(x) - beta * x)

set samples 500

plot gamma_pdf(x, alpha, beta) w l lt 1 lw 8 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "gamma1_pdf.eps"

set border 3 lw 2

set title ""

set lmargin screen 0.125
set rmargin screen 0.875

set xtics out nomirror
set xlabel 'x'
set xrange[0:20]

set ytics scale 0
set ylabel "Probability Density Function"
set format y ''

alpha = 3
beta = 0.5

gamma_pdf(x, alpha, beta) = exp(alpha * log(beta) - lgamma(alpha) + (alpha - 1) * log(x) - beta * x)

set samples 500

plot gamma_pdf(x, alpha, beta) w l lt 1 lw 8 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "gamma2_pdf.eps"

set border 3 lw 2

set title ""

set lmargin screen 0.125
set rmargin screen 0.875

set xtics out nomirror
set xlabel 'x'
set xrange[0:20]

set ytics scale 0
set ylabel "Probability Density Function"
set format y ''

alpha = 0.3
beta = 5

gamma_pdf(x, alpha, beta) = exp(alpha * log(beta) - lgamma(alpha) + (alpha - 1) * log(x) - beta * x)

set samples 500

plot gamma_pdf(x, alpha, beta) w l lt 1 lw 8 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "gamma3_pdf.eps"

set border 3 lw 2

set title ""

set lmargin screen 0.125
set rmargin screen 0.875

set xtics out nomirror
set xlabel 'x'
set xrange[0:20]

set ytics scale 0
set ylabel "Probability Density Function"
set format y ''

alpha = 0.3
beta = 0.5

gamma_pdf(x, alpha, beta) = exp(alpha * log(beta) - lgamma(alpha) + (alpha - 1) * log(x) - beta * x)

set samples 500

plot gamma_pdf(x, alpha, beta) w l lt 1 lw 8 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 6, 4
set output "gamma4_pdf.eps"

set border 3 lw 2

set title ""

set lmargin screen 0.125
set rmargin screen 0.875

set xtics out nomirror
set xlabel 'x'
set xrange[0:20]

set ytics scale 0
set ylabel "Probability Density Function"
set format y ''

alpha = 3
beta = 5

gamma_pdf(x, alpha, beta) = exp(alpha * log(beta) - lgamma(alpha) + (alpha - 1) * log(x) - beta * x)

set samples 500

plot gamma_pdf(x, alpha, beta) w l lt 1 lw 8 lc rgb "$dark" notitle

END
