#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-3:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

splot  0.5 * ( (x  - 2.474708) / exp(y) )**2 \
     + 0.5 * ( (x  - 2.075384) / exp(y) )**2 \
     + 0.5 * ( (x  - 1.847598) / exp(y) )**2 \
     + 7.63531265768 -  8.73885035992 notitle

END
