#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "prior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + log(0.0752) + log(0.02005) + 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "indiv_likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma = 0.25
y_obs = 1.30321992

N_margin = 9
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * ( (x * exp(y) - y_obs) / sigma )**2 \
      + 6.09164880571 -  8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "marginal_likelihood.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma=0.25
y_obs = 1.30321992

N_margin = 9.0
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * ( (x * exp(y) - y_obs) / sigma )**2 \
     + 0.5 * N_margin * log(sigma**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma**2 + exp(2 * y)) \
     - 5.68491191275 - 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "indiv_posterior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma=0.25
y_obs = 1.30321992

N_margin = 9.0
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + 0.5 * ( (x * exp(y) - y_obs) / sigma )**2 \
     + log(0.075) + log(0.02) + 6.09164880571 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "marginal_posterior.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

sigma=0.25
y_obs = 1.30321992

N_margin = 9.0
y_ave = -1.107945
y2_ave = 3.989815

splot  0.5 * x**2 \
     + 0.5 * (exp(y) / 3)**2 - y \
     + 0.5 * ( (x * exp(y) - y_obs) / sigma )**2 \
     + 0.5 * N_margin * log(sigma**2 + exp(2 * y)) \
     + 0.5 * N_margin * y2_ave / (sigma**2 + exp(2 * y)) \
     + log(0.075) + log(0.02) - 5.68491191275 notitle

END
