#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal pdfcairo transparent enhanced size 12in, 8in font 'Times, 60'
set output "eye_chart_regimes.pdf"

set border 3

set title ""

set xtics scale 0
set xlabel 'Posterior Shrinkage'
set xrange[0:1]

set ytics scale 0
set ylabel 'Posterior z Score'
set yrange[0:5]

set label "Ideal" at 0.7, 1.25 center tc rgb "black"
set arrow from 0.825, 0.875 rto +0.1, -0.5 lw 5 head filled

set label "Poorly\nIdentified" at 0.3, 1.5 center tc rgb "black"
set arrow from 0.175, 0.875 rto -0.1, -0.5 lw 5 head filled

set label "Prior/Observational\nConflict" at 0.3, 3.75 center tc rgb "black"
set arrow from 0.175, 4.125 rto -0.1, +0.5 lw 5 head filled

set label "Overfit" at 0.7, 3.5 center tc rgb "black"
set arrow from 0.825, 4.125 rto +0.1, +0.5 lw 5 head filled

plot 0 lc "white" notitle

END
