#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-5:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

splot  0.5 * (x * exp(-y) )**2 + y \
     + 0.5 * (exp(y) / 3)**2 - y \
     + log(0.0752) + log(0.02005) + 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "inverted_funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-15:15]

set ytics nomirror scale 0
set format y ''
set yrange[-3:5]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

splot  0.5 * (x * exp(y) )**2 - y \
     + 0.5 * (exp(-y) / 3)**2 + y \
     + log(0.0752) + log(0.02005) + 8.732925977 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "normal.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-10:10]

set ytics nomirror scale 0
set format y ''
set yrange[-10:10]

set zlabel ''
set zrange[0:40]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 200
set isosamples 200

splot 0.5 * 1.0 * x**2 + 0.5 * 1.0 * y**2 notitle

END
