#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "energy_vs_funnel.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-140:130]

set ytics nomirror scale 0
set format y ''
set yrange [-6:3]

set zlabel ''
set zrange[-20:7]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9

set samples 400
set isosamples 400

K = 25

# E ~ N(K * log(tau) + K, sqrt{K})
splot 0.5 * ( x - (K * y + K) )**2 / K notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "delta_energy.eps"

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-140:130]

set ytics nomirror scale 0
set format y ''
set yrange[0:0.1]

set samples 600

K = 25
gauss(x, mu, sigma2) = exp(-0.5 * (x - mu)**2 / sigma2) / sqrt(2 * pi * sigma2)

plot \
"+" using 1:(0):(gauss(x, 0, K)) w filledcurve lt 1 lw 1 lc rgb "$dark_highlight" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "log_tau.eps"

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-6:3]

set ytics nomirror scale 0
set format y ''
set yrange[0:2]

set samples 600

plot \
"+" using 1:(0):(exp(-0.5 * (exp(x) / 3)**2 + x)) w filledcurve lt 1 lw 1 lc rgb "$mid_highlight" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "marginal_energy.eps"

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-140:130]

set ytics nomirror scale 0
set format y ''
set yrange[0:2]

set samples 600

#set arrow from -20, 0 to -20, 2 lw 2 lc rgb "green" nohead front
#set arrow from 90, 0 to 90, 2 lw 2 lc rgb "green" nohead front

plot \
"+" using 1:(0):(1 * exp(-0.5 * (exp((x - 20) / 30) / 3)**2 + (x - 20) / 30)) \
w filledcurve lt 1 lw 1 lc rgb "$mid_highlight" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "energy_comp.eps"

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-140:130]

set ytics nomirror scale 0
set format y ''
set yrange[0:0.1]

set samples 600

K = 25
gauss(x, mu, sigma2) = exp(-0.5 * (x - mu)**2 / sigma2) / sqrt(2 * pi * sigma2)

plot \
"+" using 1:(0):(0.025 * exp(-0.5 * (exp((x - 20) / 30) / 3)**2 + (x - 20) / 30)) \
w filledcurve lt 1 lw 1 lc rgb "$mid_highlight" notitle, \
"+" using 1:(0):(gauss(x, 0, K)) w filledcurve lt 1 lw 1 lc rgb "$dark_highlight" notitle, \

END
