#!/bin/bash

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "initial_marginal.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-5:5]

set ytics nomirror scale 0
set format y ''
set yrange[-5:5]

set zlabel ''
set zrange[-2:0]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 200
set isosamples 200

tau1 = 3
tau2 = 2

splot - 0.5 * (x / tau1)**2 - 0.5 * (y / tau2)**2 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "naive_pushforward.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-5:5]

set ytics nomirror scale 0
set format y ''
set yrange[-5:5]

set zlabel ''
set zrange[-7:0]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 200
set isosamples 200

mu = -3
tau_plus = 0.5

splot - 0.5 * ( (x + y - mu) / tau_plus)**2 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "naive_product.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-5:5]

set ytics nomirror scale 0
set format y ''
set yrange[-5:5]

set zlabel ''
set zrange[-3:0]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 200
set isosamples 200

tau1 = 3
tau2 = 2

mu = -3
tau_plus = 0.5

splot - 0.5 * (x / tau1)**2 - 0.5 * (y / tau2)**2 \\
      - 0.5 * ( (x + y - mu) / tau_plus)**2 notitle

END
