#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'hazard.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[0:10]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[0:8]

set samples 400

alpha = 1.25
sigma = 2

plot (alpha / sigma) * (x / sigma)**(alpha - 1) w l lt 1 lw 5 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'cumulative_hazard.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[0:10]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[0:8]

set samples 400

alpha = 1.25
sigma = 2

plot (x / sigma)**alpha w l lt 1 lw 5 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'survival.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[0:10]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[0:1]

set samples 400

alpha = 1.25
sigma = 2

plot exp(-(x / sigma)**alpha) w l lt 1 lw 5 lc rgb "$dark" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'density.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[0:10]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[0:0.4]

set samples 400

alpha = 1.25
sigma = 2

plot (alpha / sigma) * (x / sigma)**(alpha - 1) * exp(-(x / sigma)**alpha) \
w l lt 1 lw 5 lc rgb "$dark" notitle

END
