#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "density.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-7:7]

set ytics nomirror scale 0
set format y ''
set yrange[-5:7]

set zlabel ''
set zrange[-7:0]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 400
set isosamples 400

splot \
- 0.5 * ( (x - 0.25 * y**3 + y**2 - 2) / 0.25)**2 \
- 0.5 * (x / 2)**2 - 0.5 * (y / 2)**2 notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 5, 5
set output "refined_samples.eps"

set pm3d map implicit at s

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-7:7]

set ytics nomirror scale 0
set format y ''
set yrange[-5:7]

set zlabel ''
set zrange[-7:0]

unset cbtics
unset colorbox

set palette rgbformulae 8, 9, 9 negative

set samples 300
set isosamples 300

plot \
'refined_samples.dat' u (\$1 == 0 ? \$2 : 1/ 0):3 w p pt 7 ps 1 lc rgb "$dark" notitle, \
'refined_samples.dat' u (\$1 == 1 ? \$2 : 1/ 0):3 w p pt 7 ps 1 lc rgb "green" notitle

END
