#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'realizations.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".(20 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(i) w l lt 1 lw 3 lc palette notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'realizations_few.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=3:5] "< sed -n ".(10 * 12 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(10 * i) w l lt 1 lw 3 lc palette notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'realization.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:1] "< sed -n ".(20 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(45) w l lt 1 lw 3 lc palette notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'overlay_realizations.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".(20 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(i) w l lt 1 lw 3 lc palette notitle, \
'data.csv' u 1:2 w p pt 7 ps 4 lc rgb "white" notitle, \
'data.csv' u 1:2 w p pt 7 ps 3 lc rgb "black" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'overlay_realizations_few.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=3:5] "< sed -n ".(10 * 12 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(10 * i) w l lt 1 lw 3 lc palette notitle, \
'data.csv' u 1:2 w p pt 7 ps 4 lc rgb "white" notitle, \
'data.csv' u 1:2 w p pt 7 ps 3 lc rgb "black" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'data.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-40:40]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
'data.csv' u 1:2 w p pt 7 ps 4 lc rgb "white" notitle, \
'data.csv' u 1:2 w p pt 7 ps 3 lc rgb "black" notitle

END


gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'prior_realizations.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-75:75]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".(20 * i)."p output_prior.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(i) w l lt 1 lw 3 lc palette notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 35' size 13, 8
set output 'post_realizations.eps'

set border 0

set lmargin screen 0
set bmargin screen 0
set rmargin screen 1
set tmargin screen 1

set title ""

set xlabel 'x'
set format x ''
set xtics nomirror scale 0
set xrange[-11:11]

set ytics nomirror scale 0
set format y ''
set ylabel 'y'
set yrange[-75:75]

set zlabel ''
set cbrange[-10:50]
unset cbtics
unset colorbox

set palette model RGB rgbformulae 8, 9, 9 negative

set datafile separator ','

plot \
for [i=1:50] "< sed -n ".(20 * i)."p output.clean.csv | tr ',' '\n'" \
u (22.0 * \$0 / 550 - 11):1:(i) w l lt 1 lw 3 lc palette notitle, \
'data.csv' u 1:2 w p pt 7 ps 4 lc rgb "white" notitle, \
'data.csv' u 1:2 w p pt 7 ps 3 lc rgb "black" notitle

END
