#!/bin/bash

light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "cdf_comp.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:1]

set arrow from -4.652696, 0 to -4.652696, 1 lt 1 lw 4 lc rgb "#CCCCCC" nohead
set arrow from 4.652696, 0 to 4.652696, 1 lt 1 lw 4 lc rgb "#CCCCCC" nohead

plot  \
0.01 w l lt 1 lw 4 lc rgb "#CCCCCC" notitle, \
0.99 w l lt 1 lw 4 lc rgb "#CCCCCC" notitle, \
"../density_comps.csv" u 1:2 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:3 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "density_comp.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2.25]

set arrow from -4.652696, 0 to -4.652696, 2.25 lt 1 lw 4 lc rgb "#CCCCCC" nohead
set arrow from 4.652696, 0 to 4.652696, 2.25 lt 1 lw 4 lc rgb "#CCCCCC" nohead

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "density_comp_zoom.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[4:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:0.03]

set arrow from -4.652696, 0 to -4.652696, 1 lt 1 lw 4 lc rgb "#CCCCCC" nohead
set arrow from 4.652696, 0 to 4.652696, 1 lt 1 lw 4 lc rgb "#CCCCCC" nohead

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "containment_zoom.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[8:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:0.0005]

plot \
"../density_comps.csv" u 1:8 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:12 w l lt 1 lw 4 lc rgb "$light" notitle

END


gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "containment_moderate.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:0.3]

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:4 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:8 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "contraction_moderate.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2]

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:5 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:9 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "contraction_moderate_zoom.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-3:0]

set ytics nomirror scale 0
set format y ''
set yrange [0:2]

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:5 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:9 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "compromise_moderate.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2]

plot  \
"../density_comps.csv" u 1:7 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:6 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:10 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "containment_heavy.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2.25]

plot  \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:4 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:12 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "contraction_heavy.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2.25]

plot  \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:5 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:13 w l lt 1 lw 4 lc rgb "$light" notitle

END

gnuplot << END


set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "contraction_heavy_zoom.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-3.375:0.375]

set ytics nomirror scale 0
set format y ''
set yrange [0:2.25]

plot  \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:5 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:13 w l lt 1 lw 4 lc rgb "$light" notitle

END


gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 30' size 6.25, 5
set output "compromise_heavy.eps"

set datafile separator ','

set title ""

set border 0

set lmargin screen 0.0
set rmargin screen 1.0
set bmargin screen 0.0
set tmargin screen 1.0

set xtics nomirror scale 0
set format x ''
set xrange[-18.75:18.75]

set ytics nomirror scale 0
set format y ''
set yrange [0:2.25]

plot  \
"../density_comps.csv" u 1:11 w l lt 1 lw 4 lc rgb "$dark" notitle, \
"../density_comps.csv" u 1:6 w l lt 1 lw 4 lc rgb "$mid" notitle, \
"../density_comps.csv" u 1:14 w l lt 1 lw 4 lc rgb "$light" notitle

END
