#!/bin/bash

hyperlight="#F5ECEC"
sublight="#EBDADA"
light="#DCBCBC"
light_highlight="#C79999"
mid="#B97C7C"
mid_highlight="#A25050"
dark="#8F2727"
dark_highlight="#7C0000"

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "volume_change.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:2]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

set label '{/Symbol p}(q)' at 0.05, 1.5 tc rgb "$hyperlight"
set label "dq" at 0.8, 2.55 tc rgb "$mid"

volume(x, N) = x**(N - 1)
q(V, N) = V**(1.0 / (N - 1))

N1 = 10.0
sigma2 = 1 / N1
N2 = 40.0

y=0.05
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=0.25
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=0.45
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=0.65
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=0.85
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=1.05
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=1.25
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=1.45
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=1.65
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=1.85
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=2.05
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=2.25
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=2.45
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=2.65
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

y=2.85
set arrow from q(y, N1), y to q(y, N2), y \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25 front

plot \
exp(- 0.5 * x * x / sigma2) / sqrt(2 * pi * sigma2) \
with lines lt 1 lw 4 lc rgb '$hyperlight' notitle, \
volume(x, N1) with lines lt 1 lw 4 lc rgb '$light' notitle, \
volume(x, N2) with lines lt 1 lw 4 lc rgb '$mid' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "mass_change.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:3]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:2.5]

set label '{/Symbol p}(q) dq' at 2.25, 1.0 tc rgb '$dark'

N1 = 10.0
sigma2 = 1 / N1

set arrow from 0.9, 2 to 1.3, 2 lw 4 lc rgb '$dark' nohead
set label 'D' at 1.335, 2 tc rgb '$dark'
set arrow from 1.5, 2 to 1.9, 2 lw 4 lc rgb '$dark' head filled size screen 0.01, 25

density(x, N, sigma2) =  exp(  log(2.0) - lgamma(0.5 * N) \
                        - 0.5 * N * log(2.0 * sigma2) \
                        + (N - 1) * log(x) - 0.5 * x * x / sigma2 )

set samples 200

plot \
density(x, 10, sigma2) \
with lines lt 1 lw 4 lc rgb '$light' notitle, \
density(x, 15, sigma2) \
with lines lt 1 lw 4 lc rgb '$light_highlight' notitle, \
density(x, 20, sigma2) \
with lines lt 1 lw 4 lc rgb '$mid' notitle, \
density(x, 25, sigma2) \
with lines lt 1 lw 4 lc rgb '$mid_highlight' notitle, \
density(x, 30, sigma2) \
with lines lt 1 lw 4 lc rgb '$dark' notitle, \
density(x, 35, sigma2) \
with lines lt 1 lw 4 lc rgb '$dark_highlight' notitle

END

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "normalized_mass_change.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}| / {/Symbol=\326}D'
set xrange[0:0.6]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:2]

set label '{/Symbol p}(q) dq' at 0.42, 1.0 tc rgb "$dark"

set arrow from 0.2475, 0.2 to 0.2875, 0.2 \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25
set label 'D' at 0.3, 0.2 tc rgb '$dark'
set arrow from 0.38, 0.2 to 0.34, 0.2 \
lw 4 lc rgb '$dark' head filled size screen 0.01, 25


N1 = 10.0
sigma2 = 1 / N1
N2 = 40.0

density(x, N, sigma2) =  exp(  log(2.0) - lgamma(0.5 * N) \
                        - 0.5 * N * log(2.0 * sigma2) \
                        + (N - 1) * log(x) - 0.5 * x * x / sigma2 )

set samples 200

plot \
density(x * sqrt(10), 10, sigma2) \
with lines lt 1 lw 4 lc rgb '$light' notitle, \
density(x * sqrt(15), 15, sigma2) \
with lines lt 1 lw 4 lc rgb '$light_highlight' notitle, \
density(x * sqrt(20), 20, sigma2) \
with lines lt 1 lw 4 lc rgb '$mid' notitle, \
density(x * sqrt(25), 25, sigma2) \
with lines lt 1 lw 4 lc rgb '$mid_highlight' notitle, \
density(x * sqrt(30), 30, sigma2) \
with lines lt 1 lw 4 lc rgb '$dark' notitle, \
density(x * sqrt(35), 35, sigma2) \
with lines lt 1 lw 4 lc rgb '$dark_highlight' notitle

END

exit

gnuplot << END

set terminal postscript enhanced eps color font 'Times-Roman, 40' size 5, 5
set output "mass_change.eps"

set title ""

set xtics nomirror scale 0
set format x ''
set xlabel '|q - q_{Mode}|'
set xrange[0:3]

set ytics nomirror scale 0
set format y ''
set ylabel ''
set yrange[0:3]

set label '{/Symbol p}(q) dq' at 2.35, 1.0 tc rgb "$dark"

N1 = 10.0
sigma2 = 1 / N1
N2 = 40.0

y=1.795
set arrow from 0.95, y to 1.97, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=1.59
set arrow from 1.06, y to 2.07, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=1.39
set arrow from 1.11, y to 2.12, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=1.19
set arrow from 1.16, y to 2.16, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=0.99
set arrow from 1.20, y to 2.2, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=0.79
set arrow from 1.25, y to 2.23, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=0.59
set arrow from 1.3, y to 2.3, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=0.39
set arrow from 1.36, y to 2.36, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

y=0.19
set arrow from 1.45, y to 2.45, y \
lw 4 lc rgb '$sublight' head filled size screen 0.01, 25

plot \
exp(  log(2.0) - lgamma(0.5 * N1) \
- 0.5 * N1 * log(2.0 * sigma2) \
+ (N1 - 1) * log(x) - 0.5 * x * x / sigma2 ) \
with lines lt 1 lw 4 lc rgb '$mid' notitle, \
exp(  log(2.0) - lgamma(0.5 * N2) \
- 0.5 * N2 * log(2.0 * sigma2) \
+ (N2 - 1) * log(x) - 0.5 * x * x / sigma2 ) \
with lines lt 1 lw 4 lc rgb '$dark' notitle

END
